### ISSUE TITLE
Frame support?

### ISSUE THREAD

**Issue by pixelchutes** [tuvistavie/atomic-chrome#11]
Almost embarrassed opening this issue _(don't judge!)_ :smile:

In testing this against a legacy application _(using `<frameset>`)_ it did not seem to work. 
However, when testing directly against the target page of the `<frame src>`, it worked as expected.

I'm not familiar with Chrome plugin development, perhaps this is a known limitation? (e.g. frame support)

**Comment by danhper** [comment]
Hi, thanks for reporting!
Wow, I wonder when was the last time I heard of frame and frameset :smile: 
I have no idea of what could be the issue, but I will take a look!
Is the plugin is outputting something to your console?

**Comment by pixelchutes** [comment]
Yes, the console output is:

> Atomic Chrome does not support `<frame>` (yet?) content-script.js:1

**Comment by danhper** [comment]
Thank you for the details, I am going to check it out!

**Comment by danhper** [comment]
@pixelchutes This should be fixed as of 0.2.1.
`document.activeElement` indeed returns the `frame`, and not the `textarea` or whatever, causing the issue.

I updated to get the `activeElement` inside the `frame`,
when the current one is a frame.
Keep in mind that this will not work for cross domain frames, as AFAIK there is no way to access the underlying document.

Please reopen if you are still having issues!

Thank you!

**Comment by pixelchutes** [comment]
Confirmed! Thanks @tuvistavie _(especially for the quick turnaround!)_
