### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by benadamstyles** [tuvistavie/atomic-chrome#18]
Atom package `atomic-chrome` version: `0.3.0`
Atomic Chrome extension version: `0.2.6`

Clicking the browser button does nothing. Atom is open already. I tried inspecting the extension's background page via Chrome extension manager developer mode and the devtools view opens but there is nothing there, no console logs of any kind, and I am unable to use the console to run any javascript, pressing enter in the console just clears the input. It feels like the extension just isn't initialising. Any ideas?

**Comment by danhper** [comment]
Hi, thanks for reporting.

What page were you using when you tried the plugin?
There could be some sites for which it just does not work,
although it seems weird that no window gets opened in Atom.
Do you get the same behavior with GitHub issues?

Also, could it be that you have another instance of Atom running somewhere?

If it does not seem to work, could you please try the following:

```
$ npm install -g wscat
$ wscat -c ws://localhost:64292
> {"type": "register", "payload": {"extension": ".md", "title": "Hello", "text": "some text"}}
```

This should open a new tab in Atom with written `"some text"` in it.
Could you let me know if this works or not please?

Thank you!

**Comment by benadamstyles** [comment]
Hey man I am really sorry but I just restarted my mac and it is working again. I should have tried this before posting this issue. `wscat` is doing what you said it should. I'm going to close this and assume that as the extension wasn't initialising at all, this was a chrome issue and nothing to do with your code. Thanks for the detailed response and sorry for wasting your time!

**Comment by danhper** [comment]
No problem! Thanks for the feedback :smiley:
