### ISSUE TITLE
I dont get it?

### ISSUE THREAD

**Issue by OwenMelbz** [tuvistavie/atomic-chrome#22]
Just stumbled across this and it seems loads of people enjoy it.

But I just don't get it? Whats the point/benefit of this? What problem does it solve for example? It might help my processes dramatically, if only I knew why?!

**Comment by laughedelic** [comment]
The point is that you can use your cozy Atom with all your favourite plugins to edit text in Chrome. For example, you can edit comments on Github in Atom with markdown preview, code blocks syntax highlighting and any other [related plugins](https://atom.io/packages/search?utf8=%E2%9C%93&q=keyword:markdown). For writing more than several lines it can be quite convenient.

**Comment by danhper** [comment]
I had the same question a few time on HackerNews, so I wrote about my use case there.
See my first comment.
https://news.ycombinator.com/item?id=11022356
