### ISSUE TITLE
[Bug] markdown in github online edit becomes html

### ISSUE THREAD

**Issue by aploium** [tuvistavie/atomic-chrome#23]
for example, I'm editing this markdown:
`https://github.com/tuvistavie/atomic-chrome/edit/master/README.md`

Before atomic-chrome: 

![Before atomic-chrome](https://cloud.githubusercontent.com/assets/15957250/19180128/df1989f0-8c95-11e6-8cd3-2dce6694f27f.png)

And after I click the atomic-chrome:
![After atomic-chrome](https://cloud.githubusercontent.com/assets/15957250/19180159/16456cc8-8c96-11e6-9e2f-e1af7504527e.png)

OS: windows 10 x64 Build10586.589
Browser: Chrome 53.0.2785.116 (64-bit)
Atom: 1.10.2 with default config
Atomic Chrome (chrome plugin): 0.2.6
Atomic-Chrome-Atom (Atom plugin): 0.3.0

**Comment by danhper** [comment]
Hi, thanks for reporting.
It seems there has been some changes in CodeMirror which broke the extension.
I just fixed it and uploaded it as 0.2.7, it should be available on the store soon!
