### ISSUE TITLE
Q: could you describe your development setup

### ISSUE THREAD

**Issue by hharnisc** [tuvistavie/atomic-chrome#3]
- which flavor of linux
- any other packages/plugins you've got installed

not an issue at all, but thought your setup was cool

**Comment by danhper** [comment]
Hi,

I am using [Arch Linux](https://www.archlinux.org/).
My window manager is [xmonad](http://xmonad.org/) and the top bar is [xmobar](http://projects.haskell.org/xmobar/).

If you are interested, you can find most of my config [here](https://github.com/tuvistavie/dotfiles) and [there](https://github.com/tuvistavie/atom-config)
