### ISSUE TITLE
Broken promises with site titles that cannot be file names

### ISSUE THREAD

**Issue by jeremytwfortune** [tuvistavie/atomic-chrome#30]
Invoking the extension on sites with titles that cannot wind up as file names results in promise errors in Atom.

On a site with site title `A | B`, Atom produces:

```
Uncaught (in promise) Error: EINVAL, open 'C:\Users\Jeremy\AppData\Local\Temp\A | B-117107-4480-1jk0sx1.ruequmcxr.md'
```

Removing the `|` solves the issue on Windows 10.

**Comment by danhper** [comment]
Thank you for reporting!
I fixed this on the Atom side, it should work with the latest version.

**Comment by jeremytwfortune** [comment]
Thanks!
