### ISSUE TITLE
Idea: Replace input element in browser with Atom Editor

### ISSUE THREAD

**Issue by gravitypersists** [tuvistavie/atomic-chrome#8]
Perhaps it can inherit configuration and plugins from your local editor? Is this crazy hard? I don't know. Would it be cool? Fuck yes.

**Comment by danhper** [comment]
Hi,
Thanks for the feedback.
Unfortunately, this is not possible.
There are not a lot of things you can embed in a webpage, and embedding
a native app (even if it runs on V8), is simply not doable.
I am closing for now, if I misunderstood your point, please feel free to reopen.
